### PR TITLE
Add llvm (for llvm-symbolizer) and test that AddressSanitizer output features source locations. (LDC-only)

### LINKED ISSUE #733: Add llvm-symbolizer to the path in run.dlang.org image
When using Address Sanitizer, location information is not available in the output:
https://run.dlang.io/is/H0nQKi

This can be solved by adding `llvm-symbolizer` to the path. Probably that tool is not installed by default in the docker image, so needs installation first. Should be part of the `llvm` package.

background info: https://clang.llvm.org/docs/AddressSanitizer.html#symbolizing-the-reports

### PR DESCRIPTION
**Pull request by JohanEngelen**
This fixes https://github.com/dlang-tour/core/issues/733

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]
Sorry for being so unresponsive and with little time. Thanks!

**Comment by wilzbach** [comment]
This should get out-deployed within ~ 30 minutes. Otherwise please ping me.

**Comment by JohanEngelen** [comment]
@wilzbach I still don't get debug information on run.dlang.io, although when testing on my own machine using docker run it worked, and test.sh on Travis also succeeded?

**Comment by JohanEngelen** [comment]
Use https://run.dlang.io/is/H0nQKi to test.

**Comment by JohanEngelen** [comment]
> @wilzbach I still don't get debug information on run.dlang.io, although when testing on my own machine using docker run it worked, and test.sh on Travis also succeeded?

It works on run.dlang.io now, thanks!

**Pull request merged**
